describe('The Home Page', () => {
  it('successfully loads', () => {
    cy.visit('https://teamgithubplayer.github.io/index.html') // change URL to match your dev URL
    cy.get('[data-cy="head.el_1"]').click()
    cy.get('[data-cy="head.el_2"]').click()
    cy.get('[data-cy="head.el_3"]').click()
    cy.get('[data-cy="head.el_3"]').invoke('show').click()
    cy.get('[data-cy="head.el_3a"]').click()
    cy.get('[data-cy="head.el_3"]').invoke('show').click()
    cy.get('[data-cy="head.el_3b"]').click()
    cy.get('[data-cy="head.el_3"]').invoke('show').click()
    cy.get('[data-cy="head.el_3c"]').click()
    cy.get('[data-cy="head.el_3"]').invoke('show').click()
    cy.get('[data-cy="head.el_3d"]').click()
    cy.get('[data-cy="head.el_4"]').click()
    cy.get('[data-cy="head.el_5"]').click()
    cy.get('[data-cy="head.el_6"]').click()
    cy.get('[data-cy="head.el_7"]').click()
  })
})